In [1]:
# Import pytorch and initialize a tensor
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [2]:
# Get the tensor object's shape and data type
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [3]:
x = torch.tensor([False, 1, 2.0])
print(x)
# tensor([0., 1., 2.])

tensor([0., 1., 2.])


In [4]:
# Generate a tensor object with 3 rows and 4 columns filled with zeros.
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
# Generate a tensor object with 3 rows and 4 columns filled with ones.
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
# Generate 3 rows and 4 columns of values between 0 and 10, including the low value but not the high value.
torch.randint(low=0, high=10, size=(3,4))

tensor([[1, 0, 6, 5],
        [3, 2, 9, 4],
        [2, 4, 6, 5]])

In [7]:
# Generate random numbers between 0 and 1 with 3 rows and 4 columns.
torch.rand(3, 4)

tensor([[0.8094, 0.5830, 0.3188, 0.1858],
        [0.8369, 0.9665, 0.4005, 0.2466],
        [0.8860, 0.4515, 0.8258, 0.1302]])

In [8]:
# Generate numbers that follow a normal distribution with 3 rows and 4 columns.
torch.randn((3,4))

tensor([[-1.2458,  0.8731, -1.1778,  0.9091],
        [-0.1778,  1.2952,  3.1120,  1.1815],
        [-0.2144,  0.7014,  1.6363, -1.1710]])

In [9]:
# Directly convert a NumPy array into a Torch tensor.
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
